import os
import aiohttp
from datetime import datetime
from typing import Dict, Any, Optional

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "7783653948:AAFoDMKp6moop6m3LdyUYm_xb6i-_uN8y1I")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "4207488")  # Your chat ID

class TelegramService:
    """Service for sending trading signals to Telegram"""
    
    def __init__(self):
        self.bot_token = TELEGRAM_BOT_TOKEN
        self.chat_id = TELEGRAM_CHAT_ID
        self.base_url = f"https://api.telegram.org/bot{self.bot_token}"
    
    async def send_signal(self, signal: Dict[str, Any]) -> bool:
        """Send trading signal to Telegram"""
        try:
            direction = signal.get("direction", "LONG")
            pair = signal.get("pair", "BTC/USDT")
            entry = signal.get("entry", 0)
            stop_loss = signal.get("stop_loss", 0)
            take_profit = signal.get("take_profit_1", 0)
            take_profit_2 = signal.get("take_profit_2", 0)
            confidence = signal.get("confidence", 0)
            wyckoff = signal.get("wyckoff_phase", "unknown")
            kill_zone = signal.get("kill_zone", "")
            
            emoji = "🟢" if direction == "LONG" else "🔴"
            
            message = f"""
{emoji} <b>NEW TRADING SIGNAL</b> {emoji}

📊 <b>{pair}</b> | {direction}
🎯 Confidence: <b>{confidence}%</b>

💰 <b>Entry:</b> ${entry:,.2f}
🛑 <b>Stop Loss:</b> ${stop_loss:,.2f}
✅ <b>Take Profit 1:</b> ${take_profit:,.2f}
✅ <b>Take Profit 2:</b> ${take_profit_2:,.2f}

📈 R:R Ratio: 1:{signal.get("risk_reward", 2):.1f}
🧠 Wyckoff: {wyckoff.title()}
⏰ Kill Zone: {kill_zone}

🤖 Generated by CryptoTraderAI
⏱ {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}
"""
            
            async with aiohttp.ClientSession() as session:
                url = f"{self.base_url}/sendMessage"
                payload = {
                    "chat_id": self.chat_id,
                    "text": message,
                    "parse_mode": "HTML",
                    "disable_web_page_preview": True
                }
                
                async with session.post(url, json=payload) as response:
                    if response.status == 200:
                        print(f"✅ Signal sent to Telegram: {pair} {direction}")
                        return True
                    else:
                        error = await response.text()
                        print(f"❌ Failed to send Telegram message: {error}")
                        return False
                        
        except Exception as e:
            print(f"❌ Telegram error: {e}")
            return False
    
    async def send_trade_opened(self, trade: Dict[str, Any]) -> bool:
        """Notify when trade is opened"""
        try:
            message = f"""
✅ <b>TRADE OPENED</b>

📊 {trade.get('pair', 'BTC/USDT')} | {trade.get('direction', 'LONG')}
💰 Entry: ${trade.get('entry_price', 0):,.2f}
📊 Size: {trade.get('size', 0)} contracts

⏱ {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}
"""
            
            async with aiohttp.ClientSession() as session:
                url = f"{self.base_url}/sendMessage"
                payload = {
                    "chat_id": self.chat_id,
                    "text": message,
                    "parse_mode": "HTML"
                }
                
                async with session.post(url, json=payload) as response:
                    return response.status == 200
                    
        except Exception as e:
            print(f"❌ Telegram error: {e}")
            return False
    
    async def send_trade_closed(self, trade: Dict[str, Any]) -> bool:
        """Notify when trade is closed"""
        try:
            pnl = trade.get('pnl_usdt', 0)
            pnl_emoji = "🟢" if pnl > 0 else "🔴"
            
            message = f"""
{pnl_emoji} <b>TRADE CLOSED</b> {pnl_emoji}

📊 {trade.get('pair', 'BTC/USDT')} | {trade.get('direction', 'LONG')}
💰 Entry: ${trade.get('entry_price', 0):,.2f}
💰 Exit: ${trade.get('exit_price', 0):,.2f}

📈 P&L: ${pnl:,.2f} ({trade.get('pnl_percent', 0):.2f}%)

⏱ {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}
"""
            
            async with aiohttp.ClientSession() as session:
                url = f"{self.base_url}/sendMessage"
                payload = {
                    "chat_id": self.chat_id,
                    "text": message,
                    "parse_mode": "HTML"
                }
                
                async with session.post(url, json=payload) as response:
                    return response.status == 200
                    
        except Exception as e:
            print(f"❌ Telegram error: {e}")
            return False
    
    async def send_daily_report(self, stats: Dict[str, Any]) -> bool:
        """Send daily trading report"""
        try:
            message = f"""
📊 <b>DAILY TRADING REPORT</b> 📊

📅 {datetime.utcnow().strftime("%Y-%m-%d")}

📈 Signals Generated: <b>{stats.get('signals_generated', 0)}</b>
✅ Trades Taken: <b>{stats.get('trades_taken', 0)}</b>
🎯 Win Rate: <b>{stats.get('win_rate', 0)}%</b>

💰 Total P&L: ${stats.get('total_pnl', 0):,.2f}
📊 Active Positions: <b>{stats.get('active_positions', 0)}</b>

🤖 CryptoTraderAI
"""
            
            async with aiohttp.ClientSession() as session:
                url = f"{self.base_url}/sendMessage"
                payload = {
                    "chat_id": self.chat_id,
                    "text": message,
                    "parse_mode": "HTML"
                }
                
                async with session.post(url, json=payload) as response:
                    return response.status == 200
                    
        except Exception as e:
            print(f"❌ Telegram error: {e}")
            return False

# Singleton instance
telegram_service = TelegramService()

async def send_signal_to_telegram(signal: Dict[str, Any]) -> bool:
    """Helper function to send signal"""
    return await telegram_service.send_signal(signal)
