#!/usr/bin/env python3
"""Simple signal generator that runs locally"""
import asyncio
import aiohttp
import random
from datetime import datetime

TELEGRAM_BOT_TOKEN = "7783653948:AAFoDMKp6moop6m3LdyUYm_xb6i-_uN8y1I"
TELEGRAM_CHAT_ID = "4207488"
API_URL = "https://cryptotraderai-api.onrender.com"

PAIRS = ["BTC/USDT", "ETH/USDT", "SOL/USDT"]

async def send_telegram_signal(pair, direction, entry, sl, tp):
    """Send signal to Telegram and API"""
    emoji = "🟢" if direction == "LONG" else "🔴"
    confidence = random.randint(75, 92)
    message = f"""{emoji} <b>NEW TRADING SIGNAL</b> {emoji}

📊 <b>{pair}</b> | {direction}
🎯 Confidence: <b>{confidence}%</b>

💰 <b>Entry:</b> ${entry:,.2f}
🛑 <b>Stop Loss:</b> ${sl:,.2f}
✅ <b>Take Profit:</b> ${tp:,.2f}

🤖 Generated by CryptoTraderAI
⏱ {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}"""
    
    # Send to Telegram
    async with aiohttp.ClientSession() as session:
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
        payload = {
            "chat_id": TELEGRAM_CHAT_ID,
            "text": message,
            "parse_mode": "HTML"
        }
        try:
            async with session.post(url, json=payload) as resp:
                if resp.status == 200:
                    print(f"✅ Telegram: {pair} {direction}")
                else:
                    print(f"❌ Telegram failed: {resp.status}")
        except Exception as e:
            print(f"❌ Telegram error: {e}")
        
        # Send to API for frontend
        try:
            api_payload = {
                "type": f"{direction}_FVG",
                "entry": round(entry, 2),
                "sl": round(sl, 2),
                "tp": round(tp, 2),
                "probability": f"{confidence}%",
                "symbol": pair
            }
            async with session.post(f"{API_URL}/update_signal", json=api_payload) as resp:
                if resp.status == 200:
                    print(f"✅ API updated: {pair}")
                else:
                    print(f"⚠️ API status: {resp.status}")
        except Exception as e:
            print(f"⚠️ API error: {e}")

async def generate_signal():
    """Generate random signal"""
    pair = random.choice(PAIRS)
    direction = random.choice(["LONG", "SHORT"])
    
    # Base prices
    base_prices = {
        "BTC/USDT": 67000,
        "ETH/USDT": 3500,
        "SOL/USDT": 130
    }
    
    base = base_prices[pair]
    entry = base * (1 + random.uniform(-0.02, 0.02))
    
    if direction == "LONG":
        sl = entry * 0.97
        tp = entry * 1.06
    else:
        sl = entry * 1.03
        tp = entry * 0.94
    
    await send_telegram_signal(pair, direction, entry, sl, tp)

async def main():
    """Main loop"""
    print("🚀 Local Signal Generator Started")
    print(f"⏱ Generating signals every 5-15 minutes...")
    
    while True:
        await generate_signal()
        wait = random.randint(300, 900)  # 5-15 minutes
        print(f"⏳ Next signal in {wait//60} minutes...")
        await asyncio.sleep(wait)

if __name__ == "__main__":
    asyncio.run(main())
